# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'demoapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoapp
   #pod 'BayQR', :git => 'https://github.com/bayricom/BayQR.git'

end
